from pathlib import Path

from tests.skill_test_utils import skill_path


def test_project_bootstrap_files_exist() -> None:
    assert Path("AGENTS.md").exists()
    assert Path("pyproject.toml").exists()
    assert Path("README.md").exists()
    assert Path("setup").exists()
    assert Path("skills").exists()
    assert Path("runtime/bin/qros-session").exists()
    assert Path("runtime/bin/qros-review").exists()
    assert Path("runtime/bin/qros-verify").exists()
    assert Path(".codex/INSTALL.md").exists()
    assert Path("runtime/tools/research_session.py").exists()
    assert Path("runtime/tools/review_skillgen/__init__.py").exists()
    assert Path("runtime/tools/review_skillgen/closure_models.py").exists()
    assert Path("runtime/tools/review_skillgen/context_inference.py").exists()
    assert Path("runtime/tools/review_skillgen/closure_writer.py").exists()
    assert Path("runtime/tools/review_skillgen/review_findings.py").exists()
    assert Path("runtime/tools/review_skillgen/review_engine.py").exists()
    assert Path("runtime/tools/install_runtime.py").exists()
    assert Path("runtime/scripts/run_research_session.py").exists()
    assert not Path("runtime/tools/review_skillgen/governance_signal.py").exists()
    assert not Path("runtime/tools/review_governance_runtime.py").exists()
    assert not Path("runtime/scripts/update_review_governance_candidates.py").exists()
    assert not Path("runtime/scripts/record_governance_decision.py").exists()
    assert Path("runtime/scripts/run_verification_tier.py").exists()
    assert Path("runtime/scripts/run_stage_review.py").exists()
    assert Path("runtime/scripts/scaffold_idea_intake.py").exists()
    assert Path("runtime/scripts/build_mandate_from_intake.py").exists()
    assert Path("runtime/tools/idea_runtime.py").exists()
    assert Path("runtime/tools/backtest_runtime.py").exists()
    assert Path("runtime/tools/holdout_runtime.py").exists()
    assert Path("runtime/tools/test_evidence_runtime.py").exists()
    assert Path("runtime/tools/train_runtime.py").exists()
    assert Path("contracts/intake/qualification_scorecard_schema.yaml").exists()
    assert Path("contracts/intake/idea_gate_decision_schema.yaml").exists()
    assert Path("contracts/review/review_checklist_master.yaml").exists()
    assert Path("docs/guides/installation.md").exists()
    assert Path("docs/README.codex.md").exists()
    assert Path("docs/guides/quickstart-codex.md").exists()
    assert Path("docs/guides/qros-research-session-usage.md").exists()
    assert not Path("contracts/governance/review_governance_policy.yaml").exists()
    assert not Path("docs/governance/review-governance-decision-workflow.md").exists()
    assert skill_path("qros-idea-intake-author").exists()
    assert skill_path("qros-mandate-author").exists()
    assert skill_path("qros-stage-display").exists()
    assert skill_path("qros-research-session").exists()
    assert skill_path("qros-stage-failure-handler").exists()
    assert skill_path("qros-train-freeze-author").exists()
    assert skill_path("qros-test-evidence-author").exists()
    assert skill_path("qros-backtest-ready-author").exists()
    assert skill_path("qros-holdout-validation-author").exists()
    assert Path("runtime/tools/verification_tiers.py").exists()


def test_usage_doc_exists() -> None:
    assert Path("docs/guides/codex-stage-review-skill-usage.md").exists()
    assert Path("docs/guides/closure-artifact-writer-usage.md").exists()
    assert Path("docs/guides/idea-intake-to-mandate-flow.md").exists()
    assert Path("docs/guides/qros-research-session-usage.md").exists()
    assert Path("docs/guides/qros-verification-tiers.md").exists()
    assert Path("docs/guides/stage-freeze-group-field-guide.md").exists()
    assert not Path("docs/governance/review-governance-decision-workflow.md").exists()
