from pathlib import Path


def test_project_bootstrap_files_exist() -> None:
    assert Path("AGENTS.md").exists()
    assert Path("pyproject.toml").exists()
    assert Path("README.md").exists()
    assert Path("setup").exists()
    assert Path("skills").exists()
    assert Path("bin/qros-session").exists()
    assert Path("bin/qros-review").exists()
    assert Path(".codex/INSTALL.md").exists()
    assert Path("tools/research_session.py").exists()
    assert Path("tools/review_skillgen/__init__.py").exists()
    assert Path("tools/review_skillgen/closure_models.py").exists()
    assert Path("tools/review_skillgen/context_inference.py").exists()
    assert Path("tools/review_skillgen/closure_writer.py").exists()
    assert Path("tools/review_skillgen/review_findings.py").exists()
    assert Path("tools/review_skillgen/review_engine.py").exists()
    assert Path("tools/install_runtime.py").exists()
    assert Path("scripts/run_research_session.py").exists()
    assert Path("scripts/run_stage_review.py").exists()
    assert Path("scripts/scaffold_idea_intake.py").exists()
    assert Path("scripts/build_mandate_from_intake.py").exists()
    assert Path("tools/idea_runtime.py").exists()
    assert Path("tools/backtest_runtime.py").exists()
    assert Path("tools/holdout_runtime.py").exists()
    assert Path("tools/test_evidence_runtime.py").exists()
    assert Path("tools/train_runtime.py").exists()
    assert Path("docs/intake-sop/qualification_scorecard_schema.yaml").exists()
    assert Path("docs/intake-sop/idea_gate_decision_schema.yaml").exists()
    assert Path("docs/check-sop/review_checklist_master.yaml").exists()
    assert Path("docs/experience/installation.md").exists()
    assert Path("docs/README.codex.md").exists()
    assert Path("docs/experience/quickstart-codex.md").exists()
    assert Path("docs/experience/qros-research-session-usage.md").exists()
    assert Path("skills/qros-idea-intake-author/SKILL.md").exists()
    assert Path("skills/qros-mandate-author/SKILL.md").exists()
    assert Path("skills/qros-research-session/SKILL.md").exists()
    assert Path("skills/qros-stage-failure-handler/SKILL.md").exists()
    assert Path("skills/qros-train-freeze-author/SKILL.md").exists()
    assert Path("skills/qros-test-evidence-author/SKILL.md").exists()
    assert Path("skills/qros-backtest-ready-author/SKILL.md").exists()
    assert Path("skills/qros-holdout-validation-author/SKILL.md").exists()


def test_usage_doc_exists() -> None:
    assert Path("docs/experience/codex-stage-review-skill-usage.md").exists()
    assert Path("docs/experience/closure-artifact-writer-usage.md").exists()
    assert Path("docs/experience/idea-intake-to-mandate-flow.md").exists()
    assert Path("docs/experience/qros-research-session-usage.md").exists()
    assert Path("docs/experience/stage-freeze-group-field-guide.md").exists()
