from pathlib import Path

from tests.helpers.skill_test_utils import skill_path


def test_project_bootstrap_files_exist() -> None:
    assert Path("AGENTS.md").exists()
    assert Path("pyproject.toml").exists()
    assert Path("README.md").exists()
    assert Path("setup").exists()
    assert Path("skills").exists()
    assert Path("runtime/bin/qros-session").exists()
    assert Path("runtime/bin/qros-resume").exists()
    assert Path("runtime/bin/qros-audit-reviewer").exists()
    assert Path("runtime/bin/qros-check-stage-entry").exists()
    assert Path("runtime/bin/qros-start-review").exists()
    assert Path("runtime/bin/qros-review").exists()
    assert Path("runtime/bin/qros-review-cycle").exists()
    assert Path("runtime/bin/qros-verify").exists()
    assert Path("runtime/bin/qros-validate-stage").exists()
    assert Path("runtime/bin/qros-agent-eval").exists()
    assert Path("runtime/bin/qros-update").exists()
    assert Path("runtime/bin/qros-factor-diagnostics").exists()
    assert Path(".codex/INSTALL.md").exists()
    assert Path("runtime/tools/research_session.py").exists()
    assert Path("runtime/tools/review_skillgen/__init__.py").exists()
    assert Path("runtime/tools/review_skillgen/closure_models.py").exists()
    assert Path("runtime/tools/review_skillgen/context_inference.py").exists()
    assert Path("runtime/tools/review_skillgen/closure_writer.py").exists()
    assert Path("runtime/tools/review_skillgen/review_findings.py").exists()
    assert Path("runtime/tools/review_skillgen/review_engine.py").exists()
    assert Path("runtime/tools/install_runtime.py").exists()
    assert Path("runtime/tools/stage_entry_guard.py").exists()
    assert Path("runtime/tools/stage_evaluator.py").exists()
    assert Path("runtime/tools/update_runtime.py").exists()
    assert Path("runtime/tools/factor_diagnostics.py").exists()
    assert Path("runtime/scripts/run_research_session.py").exists()
    assert Path("runtime/scripts/evaluate_stage.py").exists()
    assert Path("runtime/scripts/run_qros_update.py").exists()
    assert Path("runtime/scripts/run_factor_diagnostics.py").exists()
    assert not Path("runtime/tools/review_skillgen/governance_signal.py").exists()
    assert not Path("runtime/tools/review_governance_runtime.py").exists()
    assert not Path("runtime/scripts/update_review_governance_candidates.py").exists()
    assert not Path("runtime/scripts/record_governance_decision.py").exists()
    assert not (Path("runtime") / "bin" / "qros-paper-to-spec").exists()
    assert not (Path("runtime") / "bin" / ("qros-paper-to-spec" + "-baseline")).exists()
    assert not (Path("runtime") / "tools" / "paper_to_spec.py").exists()
    assert not (Path("runtime") / "tools" / "paper_to_spec_baseline.py").exists()
    assert not (Path("runtime") / "scripts" / ("run_paper" + "_to_spec.py")).exists()
    assert not (Path("runtime") / "scripts" / ("run_paper" + "_to_spec_baseline.py")).exists()
    assert Path("runtime/scripts/run_verification_tier.py").exists()
    assert Path("runtime/scripts/validate_stage_artifacts.py").exists()
    assert Path("runtime/scripts/run_agent_behavior_eval.py").exists()
    assert Path("runtime/scripts/run_stage_review.py").exists()
    assert Path("runtime/scripts/start_review_cycle.py").exists()
    assert Path("runtime/scripts/check_stage_entry.py").exists()
    assert Path("runtime/scripts/audit_reviewer_write_scope.py").exists()
    assert Path("templates/research-repo/AGENTS.md.tmpl").exists()
    assert Path("runtime/tools/artifact_contract_runtime.py").exists()
    assert Path("runtime/tools/agent_behavior_eval.py").exists()
    assert Path("runtime/tools/backtest_runtime.py").exists()
    assert Path("runtime/tools/holdout_runtime.py").exists()
    assert Path("runtime/tools/test_evidence_runtime.py").exists()
    assert Path("runtime/tools/train_runtime.py").exists()
    assert Path("contracts/artifacts/mandate_admission_artifacts.yaml").exists()
    assert Path("contracts/artifacts/mandate_artifacts.yaml").exists()
    assert Path("contracts/artifacts/csf_data_ready_artifacts.yaml").exists()
    assert Path("contracts/artifacts/csf_signal_ready_artifacts.yaml").exists()
    assert Path("contracts/artifacts/csf_train_freeze_artifacts.yaml").exists()
    assert Path("contracts/agent_eval/qros_agent_behavior_eval_cases.yaml").exists()
    assert Path("contracts/paper_to_spec/paper_data_spec_contract.yaml").exists()
    assert Path("contracts/paper_to_spec/paper_signal_spec_contract.yaml").exists()
    assert Path("contracts/paper_to_spec/paper_train_freeze_spec_contract.yaml").exists()
    assert Path("contracts/paper_to_spec/paper_test_evidence_spec_contract.yaml").exists()
    assert Path("runtime/tools/paper_data_spec_runtime.py").exists()
    assert Path("runtime/scripts/validate_paper_data_spec.py").exists()
    assert Path("runtime/tools/paper_signal_spec_runtime.py").exists()
    assert Path("runtime/scripts/validate_paper_signal_spec.py").exists()
    assert Path("runtime/tools/paper_train_freeze_spec_runtime.py").exists()
    assert Path("runtime/scripts/validate_paper_train_freeze_spec.py").exists()
    assert not (Path("contracts") / "paper_to_spec" / ("strategy_" + "spec_contract.yaml")).exists()
    assert Path("contracts/review/review_checklist_master.yaml").exists()
    assert Path("contracts/stages/stage_evaluator.schema.json").exists()
    assert Path("docs/guides/installation.md").exists()
    assert Path("docs/README.codex.md").exists()
    assert Path("docs/guides/quickstart-codex.md").exists()
    assert Path("docs/guides/qros-paper-to-spec-usage.md").exists()
    assert Path("docs/guides/qros-research-session-usage.md").exists()
    assert not Path("contracts/governance/review_governance_policy.yaml").exists()
    assert not Path("docs/governance/review-governance-decision-workflow.md").exists()
    assert skill_path("qros-mandate-author").exists()
    assert skill_path("qros-stage-display").exists()
    assert skill_path("qros-research-session").exists()
    assert skill_path("qros-update").exists()
    assert skill_path("qros-stage-failure-handler").exists()
    assert skill_path("qros-train-freeze-author").exists()
    assert skill_path("qros-test-evidence-author").exists()
    assert skill_path("qros-backtest-ready-author").exists()
    assert skill_path("qros-holdout-validation-author").exists()
    assert Path("skills/core/qros-paper-to-spec/SKILL.md").exists()
    assert skill_path("qros-paper-to-spec").exists()
    assert Path("runtime/tools/verification_tiers.py").exists()


def test_usage_doc_exists() -> None:
    assert Path("docs/guides/codex-stage-review-skill-usage.md").exists()
    assert Path("docs/guides/closure-artifact-writer-usage.md").exists()
    assert Path("docs/guides/mandate-admission-flow.md").exists()
    assert Path("docs/guides/qros-research-session-usage.md").exists()
    assert Path("docs/guides/qros-verification-tiers.md").exists()
    assert Path("docs/guides/stage-freeze-group-field-guide.md").exists()
    assert Path("docs/guides/qros-agent-behavior-eval.md").exists()
    assert not Path("docs/governance/review-governance-decision-workflow.md").exists()
