from __future__ import annotations

import importlib
from pathlib import Path
import textwrap

import yaml

from runtime.tools.stage_program_scaffold import STAGE_PROGRAM_SPECS


def _render_fixture_run_stage_py(*, repo_root: Path, module: str, function: str) -> str:
    return textwrap.dedent(
        f"""\
        #!/usr/bin/env python3
        from __future__ import annotations

        import argparse
        from pathlib import Path
        import sys

        ROOT = Path({repr(str(repo_root))})
        if str(ROOT) not in sys.path:
            sys.path.insert(0, str(ROOT))

        from tests.helpers.fixture_stage_program_support import run_fixture_stage_program


        def _invoke_fixture_builder(lineage_root: Path) -> None:
            # 这里保留测试专用的本地编排，避免入口退化成纯框架薄包装。
            run_fixture_stage_program({repr((module, function))}, lineage_root)


        def main() -> int:
            parser = argparse.ArgumentParser()
            parser.add_argument("--lineage-root", type=Path, required=True)
            args = parser.parse_args()
            _invoke_fixture_builder(args.lineage_root.resolve())
            return 0


        if __name__ == "__main__":
            raise SystemExit(main())
        """
    )


def run_fixture_stage_program(builder_ref: str | tuple[str, str], lineage_root: Path) -> Path:
    stage_key: str | None
    if isinstance(builder_ref, tuple):
        module_name, function_name = builder_ref
        stage_key = next(
            (
                key
                for key, spec in STAGE_PROGRAM_SPECS.items()
                if spec["module"] == module_name and spec["function"] == function_name
            ),
            None,
        )
    else:
        stage_key = builder_ref if builder_ref in STAGE_PROGRAM_SPECS else None

    if stage_key is None:
        raise ValueError(f"unknown fixture stage builder: {builder_ref}")

    spec = STAGE_PROGRAM_SPECS[stage_key]
    module = importlib.import_module(str(spec["module"]))
    builder = getattr(module, str(spec["function"]))
    return builder(lineage_root.resolve())


def materialize_fixture_stage_program(
    lineage_root: Path,
    stage_key: str,
    *,
    authored_by_agent_id: str = "test-agent",
    authored_by_agent_role: str = "executor",
    authoring_session_id: str = "test-session",
) -> Path:
    # 只给测试用：显式 materialize fixture program，不走生产 session 路径。
    spec = STAGE_PROGRAM_SPECS[stage_key]
    program_dir = lineage_root.resolve() / spec["program_dir"]
    program_dir.mkdir(parents=True, exist_ok=True)
    (program_dir / "README.md").write_text(
        f"# {stage_key} stage program\n\nGenerated by production runtime helper.\n",
        encoding="utf-8",
    )
    entrypoint = program_dir / "run_stage.py"
    entrypoint.write_text(
        _render_fixture_run_stage_py(
            repo_root=Path(__file__).resolve().parents[2],
            module=str(spec["module"]),
            function=str(spec["function"]),
        ),
        encoding="utf-8",
    )
    entrypoint.chmod(0o755)
    manifest: dict[str, object] = {
        "stage_id": spec["stage_id"],
        "route": spec["route"],
        "lineage_id": lineage_root.resolve().name,
        "entrypoint": "run_stage.py",
        "entry_type": "python",
        "inputs": [{"kind": "artifact", "path": path, "required": True} for path in spec["inputs"]],
        "outputs": [{"kind": "machine", "path": path, "required": True} for path in spec["outputs"]],
        "depends_on_programs": ["mandate"] if stage_key != "mandate" else [],
        "shared_libs": [],
        "authored_by": {
            "agent_id": authored_by_agent_id,
            "agent_role": authored_by_agent_role,
            "session_id": authoring_session_id,
        },
    }
    (program_dir / "stage_program.yaml").write_text(yaml.safe_dump(manifest, sort_keys=False, allow_unicode=True), encoding="utf-8")
    return program_dir
